/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/ray-operator/pkg/ray-controller/k8s/apis/ray.io/v1"
	scheme "github.com/ray-operator/pkg/ray-controller/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RaysGetter has a method to return a RayInterface.
// A group's client should implement this interface.
type RaysGetter interface {
	Rays(namespace string) RayInterface
}

// RayInterface has methods to work with Ray resources.
type RayInterface interface {
	Create(*v1.Ray) (*v1.Ray, error)
	Update(*v1.Ray) (*v1.Ray, error)
	UpdateStatus(*v1.Ray) (*v1.Ray, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Ray, error)
	List(opts metav1.ListOptions) (*v1.RayList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Ray, err error)
	RayExpansion
}

// rays implements RayInterface
type rays struct {
	client rest.Interface
	ns     string
}

// newRays returns a Rays
func newRays(c *RayV1Client, namespace string) *rays {
	return &rays{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the ray, and returns the corresponding ray object, and an error if there is any.
func (c *rays) Get(name string, options metav1.GetOptions) (result *v1.Ray, err error) {
	result = &v1.Ray{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rays").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Rays that match those selectors.
func (c *rays) List(opts metav1.ListOptions) (result *v1.RayList, err error) {
	result = &v1.RayList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rays").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rays.
func (c *rays) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rays").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a ray and creates it.  Returns the server's representation of the ray, and an error, if there is any.
func (c *rays) Create(ray *v1.Ray) (result *v1.Ray, err error) {
	result = &v1.Ray{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rays").
		Body(ray).
		Do().
		Into(result)
	return
}

// Update takes the representation of a ray and updates it. Returns the server's representation of the ray, and an error, if there is any.
func (c *rays) Update(ray *v1.Ray) (result *v1.Ray, err error) {
	result = &v1.Ray{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rays").
		Name(ray.Name).
		Body(ray).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *rays) UpdateStatus(ray *v1.Ray) (result *v1.Ray, err error) {
	result = &v1.Ray{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rays").
		Name(ray.Name).
		SubResource("status").
		Body(ray).
		Do().
		Into(result)
	return
}

// Delete takes name of the ray and deletes it. Returns an error if one occurs.
func (c *rays) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rays").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rays) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rays").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched ray.
func (c *rays) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Ray, err error) {
	result = &v1.Ray{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rays").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
